// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTAKkSyS7tavVcB9ta_xc48JJ4etmuo_0',
    appId: '1:277170346531:web:54870e65004e01184c2f96',
    messagingSenderId: '277170346531',
    projectId: 'uas-mobile-80124',
    authDomain: 'uas-mobile-80124.firebaseapp.com',
    storageBucket: 'uas-mobile-80124.appspot.com',
    measurementId: 'G-S1GKY0JD69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcNLYOR4vKUt_ZkBlQXWCYzspdwc2jFzE',
    appId: '1:277170346531:android:ead1820ae61297994c2f96',
    messagingSenderId: '277170346531',
    projectId: 'uas-mobile-80124',
    storageBucket: 'uas-mobile-80124.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBElEUoIoiB8lrK78fxzauzfJXqWLohlY4',
    appId: '1:277170346531:ios:6bdc07d0b4e00aee4c2f96',
    messagingSenderId: '277170346531',
    projectId: 'uas-mobile-80124',
    storageBucket: 'uas-mobile-80124.appspot.com',
    iosClientId: '277170346531-rovhfet1kejopp5o9brc8tvfri4sphs5.apps.googleusercontent.com',
    iosBundleId: 'com.example.uasFp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBElEUoIoiB8lrK78fxzauzfJXqWLohlY4',
    appId: '1:277170346531:ios:6bdc07d0b4e00aee4c2f96',
    messagingSenderId: '277170346531',
    projectId: 'uas-mobile-80124',
    storageBucket: 'uas-mobile-80124.appspot.com',
    iosClientId: '277170346531-rovhfet1kejopp5o9brc8tvfri4sphs5.apps.googleusercontent.com',
    iosBundleId: 'com.example.uasFp',
  );
}
